apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: pipeline-threescale-publish
metadata:
  annotations:
    description: three scale environment parameters Pipeline
  name: pipeline-threescale-publish
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      name: pipeline-threescale-publish
    name: pipeline-threescale-publish
  spec:
    output: null
    postCommit: null
    resources: null
    runPolicy: Serial
    source:
      type: None
    source:
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_BRANCH}
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: jenkins-publish-3scale-ansible
        env:
        - name: GIT_BRANCH
          value: ${GIT_BRANCH}
        - name: GIT_REPO
          value: ${GIT_REPO}
        - name: ANSIBLE_TEST_INVENTORY
          value: ${ANSIBLE_TEST_INVENTORY}
        - name: ANSIBLE_PROD_INVENTORY
          value: ${ANSIBLE_PROD_INVENTORY}
        - name: ANSIBLE_JOB_TEMPLATE
          value: ${ANSIBLE_JOB_TEMPLATE}
        - name: ANSIBLE_TOWER_SERVER
          value: ${ANSIBLE_TOWER_SERVER}
        - name: ROUTE_SERVICE_NAME
          value: ${ROUTE_SERVICE_NAME}
        - name: WILDCARD_DOMAIN
          value: ${WILDCARD_DOMAIN}
        - name: MAJOR_VERSION
          value: ${MAJOR_VERSION}
        - name: API_URL
          value: ${API_URL}
        - name: SWAGGER_FILE_NAME
          value: ${SWAGGER_FILE_NAME}
        - name: ANSIBLE_SMOKE_TEST_OPREATION
          value: ${ANSIBLE_SMOKE_TEST_OPREATION}
        - name: API_CAST_ROUTE_TEMPLATE_FILE
          value: ${API_CAST_ROUTE_TEMPLATE_FILE}
        - name: THREESCALE_OPENSHIFT_PROJECT
          value: ${THREESCALE_OPENSHIFT_PROJECT}

parameters:
- name: GIT_REPO
  value: https://github.com/redhatHameed/3ScaleFuseAMQ.git
  required: true
- name: GIT_BRANCH
  value: master
  required: true
- name: API_URL
  value: maingateway-service-cicddemo.app.rhdp.ocp.cloud.lab.eng.bos.redhat.com:80
  required: true
- name: WILDCARD_DOMAIN
  displayName: Threescale cicd wildcard domain
  required: true
  value: app.rhdp.ocp.cloud.lab.eng.bos.redhat.com
  description: Threescale cicd wildcard domain to generate API cast route
- name: MAJOR_VERSION
  displayName: Threescale API CAST Major Version
  required: true
  value: "1"
  description: Threescale API Cast version
- name: SWAGGER_FILE_NAME
  displayName: SWAGGER_FILE_NAME
  required: true
  value: openapi-spec.yaml
  description: SWAGGER_FILE_NAME for 3Scale env
- name: ANSIBLE_TEST_INVENTORY
  value: 3scale-test
  required: true
- name: ANSIBLE_PROD_INVENTORY
  value: 3scale-prod
  required: true
- name: ANSIBLE_JOB_TEMPLATE
  value: Deploy an API to 3scale
  required: true
- name: ANSIBLE_TOWER_SERVER
  value: tower
  required: true
- name: ANSIBLE_SMOKE_TEST_OPREATION
  value: route2
  required: false
- name: ROUTE_SERVICE_NAME
  value: 3scale-prod
  required: true
- name: API_CAST_ROUTE_TEMPLATE_FILE
  displayName: API_CAST_ROUTE_TEMPLATE_FILE 
  required: true
  value: https://github.com/redhatHameed/IntegrationApp-Automation/blob/master/apicast-routes-template.yaml
  description: apicast route template file used to create the routes
- name: THREESCALE_OPENSHIFT_PROJECT
  displayName: The Name of API CAST Gateway Project or 3scale project name deployed on Openshift to create the routes
  required: true
  value: ah-3scale-ansible
  description: apicast route template file used to create the routes



















